### ISSUE TITLE
Let's get in contact

### ISSUE THREAD

**Issue by Hungry-Dolphin** [Hungry-Dolphin/Encode#1]
Since Github has removed the private message feature I have to use this to get into contact with you. 
I see you starred my repo @Map987 
Wanna chat about anime encoding and stuff? 
if so leme know. I'll drop my contact info

**Comment by Map987** [comment]
@Hungry-Dolphin Hi, I'm just looking for some filters and tools, and now I want to know how rescaling and the like work

**Comment by Hungry-Dolphin** [comment]
@Map987 Sure, let's chat. 
I would rather not leave my tag in a public issue. So here is a discord server which I just created and I'm the only member of. 
https://discord.gg/tyd59Nwp
The link expires in 7 days so I hope you see it before then.
